# Only for backward compatibility, migrate ASAP your project includes to templates included here!

include:
  - local: '/deployment-service/functional-unit/_docker-deploy.yml'
  - local: '/deprecation-warning.yml'
