include:
  - local: '/_deployment.yml'

.deploy:
  variables:
    SERVICES_TO_CHECK: ${CI_PROJECT_NAME}_${CI_PROJECT_NAME}-${FUNCTIONAL_UNIT_MICROSERVICE_NAME}

.deploy-microservice:
  environment: &deploy-microservice-environment
    url: https://${PUBLIC_HOSTNAME}/api/${CI_PROJECT_NAME}/${FUNCTIONAL_UNIT_MICROSERVICE_NAME}

.deploy-microservice-development:
  extends: .deploy-development
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}-${FUNCTIONAL_UNIT_MICROSERVICE_NAME}.tmpl.yml:docker-compose.${CI_PROJECT_NAME}-${FUNCTIONAL_UNIT_MICROSERVICE_NAME}.dev.yml
    SPRING_PROFILES_ACTIVE: pre
    DD_SPRING_PROFILES_ACTIVE: pre
  environment:
    name: dev/${CI_PROJECT_NAME}-${FUNCTIONAL_UNIT_MICROSERVICE_NAME}
    <<: *deploy-microservice-environment

.deploy-microservice-production:
  extends: .deploy-production
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}-${FUNCTIONAL_UNIT_MICROSERVICE_NAME}.tmpl.yml:docker-compose.${CI_PROJECT_NAME}-${FUNCTIONAL_UNIT_MICROSERVICE_NAME}.prod.yml
    SPRING_PROFILES_ACTIVE: prod
    DD_SPRING_PROFILES_ACTIVE: prod
  environment:
    name: pro/${CI_PROJECT_NAME}-${FUNCTIONAL_UNIT_MICROSERVICE_NAME}
    <<: *deploy-microservice-environment

.deploy-commands:
  variables: &deploy-commands-variables
    FUNCTIONAL_UNIT_MICROSERVICE_NAME: commands
    STATUS_CHECK_DELAY: 300

.deploy-view:
  variables: &deploy-view-variables
    FUNCTIONAL_UNIT_MICROSERVICE_NAME: view
    STATUS_CHECK_DELAY: 180

.deploy-commands-development:
  extends: .deploy-microservice-development
  variables:
    <<: *deploy-commands-variables

.deploy-commands-production:
  extends: .deploy-microservice-production
  variables:
    <<: *deploy-commands-variables

.deploy-view-development:
  extends: .deploy-microservice-development
  variables:
    <<: *deploy-view-variables

.deploy-view-production:
  extends: .deploy-microservice-production
  variables:
    <<: *deploy-view-variables
