include:
  - local: '/_deployment.yml'

.deploy-support-branch: &deploy-support-branch
  only:
    - branches
  except:
    - master
    - schedules

deploy-support-branch-development:
  extends: .deploy-development
  <<: *deploy-support-branch

.deploy-stable-branch: &deploy-stable-branch
  only:
    - master
  except:
    - schedules

deploy-stable-branch-development:
  extends: .deploy-development
  <<: *deploy-stable-branch

deploy-stable-branch-production:
  extends: .deploy-production
  <<: *deploy-stable-branch

.deploy-tag: &deploy-tag
  only:
    - tags

deploy-tag-development:
  extends: .deploy-development
  <<: *deploy-tag

deploy-tag-production:
  extends: .deploy-production
  <<: *deploy-tag
