include:
  - local: '/_deployment.yml'

deploy-support-branch-development:
  extends: .deploy-support-branch-development

deploy-stable-branch-development:
  extends: .deploy-stable-branch-development

deploy-stable-branch-production:
  extends: .deploy-stable-branch-production
