include:
  - local: '/_deployment-external-service.yml'

.deploy-external-service:
  variables:
    EXTERNAL_SERVICE_PROJECT_ID: 7278179

.deploy-backup-postgresql-development:
  environment: &deploy-backup-postgresql-development-environment
    name: dev/backup-postgresql

.deploy-backup-postgresql-production:
  environment: &deploy-backup-postgresql-production-environment
    name: pro/backup-postgresql

deploy-backup-postgresql-support-branch-development:
  extends: .deploy-external-service-support-branch-development
  environment:
    <<: *deploy-backup-postgresql-development-environment

deploy-backup-postgresql-stable-branch-development:
  extends: .deploy-external-service-stable-branch-development
  environment:
    <<: *deploy-backup-postgresql-development-environment

deploy-backup-postgresql-stable-branch-production:
  extends: .deploy-external-service-stable-branch-production
  environment:
    <<: *deploy-backup-postgresql-production-environment

deploy-backup-postgresql-tag-development:
  extends: .deploy-external-service-tag-development
  environment:
    <<: *deploy-backup-postgresql-development-environment

deploy-backup-postgresql-tag-production:
  extends: .deploy-external-service-tag-production
  environment:
    <<: *deploy-backup-postgresql-production-environment
