include:
  - local: '/_deployment-functional-unit.yml'

deploy-commands-support-branch-development:
  extends: .deploy-commands-development
  only:
    - branches
  except:
    - master
    - schedules

deploy-commands-stable-branch-development:
  extends: .deploy-commands-development
  only:
    - master
  except:
    - schedules

deploy-commands-stable-branch-production:
  extends: .deploy-commands-production
  only:
    - master
  except:
    - schedules

deploy-commands-version-development:
  extends: .deploy-commands-development
  only:
    - ${DEPLOY_VERSION_TAG_REGEX}
  except:
    - branches
    - schedules

deploy-commands-version-production:
  extends: .deploy-commands-production
  only:
    - ${DEPLOY_VERSION_TAG_REGEX}
  except:
    - branches
    - schedules

deploy-view-support-branch-development:
  extends: .deploy-view-development
  only:
    - branches
  except:
    - master
    - schedules

deploy-view-stable-branch-development:
  extends: .deploy-view-development
  only:
    - master
  except:
    - schedules

deploy-view-stable-branch-production:
  extends: .deploy-view-production
  only:
    - master
  except:
    - schedules

deploy-view-version-development:
  extends: .deploy-view-development
  only:
    - ${DEPLOY_VERSION_TAG_REGEX}
  except:
    - branches
    - schedules

deploy-view-version-production:
  extends: .deploy-view-production
  only:
    - ${DEPLOY_VERSION_TAG_REGEX}
  except:
    - branches
    - schedules
