include:
  - local: '/_deployment-functional-unit.yml'

.deploy-support-branch: &deploy-support-branch
  only:
    - branches
  except:
    - master
    - schedules

deploy-commands-support-branch-development:
  extends: .deploy-commands-development
  <<: *deploy-support-branch

deploy-view-support-branch-development:
  extends: .deploy-view-development
  <<: *deploy-support-branch

.deploy-stable-branch: &deploy-stable-branch
  only:
    - master
  except:
    - schedules

deploy-commands-stable-branch-development:
  extends: .deploy-commands-development
  <<: *deploy-stable-branch

deploy-commands-stable-branch-production:
  extends: .deploy-commands-production
  <<: *deploy-stable-branch

deploy-view-stable-branch-development:
  extends: .deploy-view-development
  <<: *deploy-stable-branch

deploy-view-stable-branch-production:
  extends: .deploy-view-production
  <<: *deploy-stable-branch

.deploy-tag: &deploy-tag
  only:
    - tags

deploy-commands-tag-development:
  extends: .deploy-commands-development
  <<: *deploy-tag

deploy-commands-tag-production:
  extends: .deploy-commands-production
  <<: *deploy-tag

deploy-view-tag-development:
  extends: .deploy-view-development
  <<: *deploy-tag

deploy-view-tag-production:
  extends: .deploy-view-production
  <<: *deploy-tag
