include:
  - local: '/_deployment.yml'

.deploy-development-functional-unit: &deploy-development-functional-unit
  extends: .deploy-development

.deploy-production-functional-unit: &deploy-production-functional-unit
  extends: .deploy-production

.deploy-support-branch-development-functional-unit: &deploy-support-branch-development-functional-unit
  extends: .deploy-support-branch-development

.deploy-stable-branch-development-functional-unit: &deploy-stable-branch-development-functional-unit
  extends: .deploy-stable-branch-development

.deploy-stable-branch-production-functional-unit: &deploy-stable-branch-production-functional-unit
  extends: .deploy-stable-branch-production

.deploy-commands:
  extends: .deploy
  variables:
    SERVICES_TO_CHECK: ${STACK}_${CI_PROJECT_NAME}-commands

.deploy-view:
  extends: .deploy
  variables:
    SERVICES_TO_CHECK: ${STACK}_${CI_PROJECT_NAME}-view

.deploy-commands-development:
  <<: *deploy-development-functional-unit
  extends: .deploy-commands
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}-commands.tmpl.yml:docker-compose.${CI_PROJECT_NAME}-commands.dev.yml
    SPRING_PROFILES_ACTIVE: pre
  environment:
    name: dev/${CI_PROJECT_NAME}-commands

.deploy-view-development:
  <<: *deploy-development-functional-unit
  extends: .deploy-view
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}-view.tmpl.yml:docker-compose.${CI_PROJECT_NAME}-view.dev.yml
    SPRING_PROFILES_ACTIVE: pre
  environment:
    name: dev/${CI_PROJECT_NAME}-view

.deploy-commands-production:
  <<: *deploy-production-functional-unit
  extends: .deploy-commands
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}-commands.tmpl.yml:docker-compose.${CI_PROJECT_NAME}-commands.prod.yml
    SPRING_PROFILES_ACTIVE: prod
  environment:
    name: pro/${CI_PROJECT_NAME}-commands

.deploy-view-production:
  <<: *deploy-production-functional-unit
  extends: .deploy-view
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}-view.tmpl.yml:docker-compose.${CI_PROJECT_NAME}-view.prod.yml
    SPRING_PROFILES_ACTIVE: prod
  environment:
    name: pro/${CI_PROJECT_NAME}-view

deploy-commands-support-branch-development:
  <<: *deploy-support-branch-development-functional-unit
  extends: .deploy-commands-development

deploy-commands-stable-branch-development:
  <<: *deploy-stable-branch-development-functional-unit
  extends: .deploy-commands-development

deploy-commands-stable-branch-production:
  <<: *deploy-stable-branch-production-functional-unit
  extends: .deploy-commands-production

deploy-view-support-branch-development:
  <<: *deploy-support-branch-development-functional-unit
  extends: .deploy-view-development

deploy-view-stable-branch-development:
  <<: *deploy-stable-branch-development-functional-unit
  extends: .deploy-view-development

deploy-view-stable-branch-production:
  <<: *deploy-stable-branch-production-functional-unit
  extends: .deploy-view-production
