include:
  - local: '/deploy/dast/_zap.yml'

🛡 dast-zap-branch:
  extends:
    - .dast-zap
    - .dast-branch-rules

🛡 dast-zap-tag:
  extends:
    - .dast-zap
    - .dast-tag-rules

🛡 dast-zap-schedule:
  extends:
    - .dast-zap
    - .dast-schedule-rules
