.docker-env:
  image: ${PACKAGING_IMAGE_NAME}:${PACKAGING_IMAGE_TAG}
  variables:
    PACKAGING_IMAGE_NAME: docker
    PACKAGING_IMAGE_TAG: latest
    DIND_IMAGE_NAME: docker
    DIND_IMAGE_TAG: dind
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  services:
    - ${DIND_IMAGE_NAME}:${DIND_IMAGE_TAG}

lint-dockerfile:
  extends: .docker-env
  stage: pre-package
  dependencies: []
  variables:
    LINT_IMAGE_NAME: hadolint/hadolint
    LINT_IMAGE_TAG: latest
    DOCKERFILE_NAME: Dockerfile
  before_script:
    - >
      echo "Find Dockerfile in depth automatically by file name ..";
      if [ -z "${DOCKERFILE_PATH}" ];
      then
        dockerfilePath=$(find -name "${DOCKERFILE_NAME}");
        if [ -f "${dockerfilePath}" ];
        then
          echo "Detected '${dockerfilePath}' Dockerfile, nice!";
          export DOCKERFILE_PATH="${dockerfilePath}";
        else
          echo "DOCKERFILE_PATH is undefined and Dockerfile with name '${DOCKERFILE_NAME}' not found in project!";
          exit 1;
        fi;
      else
        echo "DOCKERFILE_PATH is defined, omitting automatic lookup";
      fi;
  script:
    - docker run --rm -i ${LINT_IMAGE_NAME}:${LINT_IMAGE_TAG} < "${DOCKERFILE_PATH}";
  allow_failure: true
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH
