include:
  - local: '/deploy/service/_docker-deploy.yml'

🤞 deploy-dev:
  extends:
    - .docker-deploy
    - .deploy-development
    - .deploy-branch-rules

👍 deploy-dev:
  extends:
    - .docker-deploy
    - .deploy-development
    - .deploy-tag-rules

🚀 deploy-pro:
  extends:
    - .docker-deploy
    - .deploy-production
    - .deploy-tag-rules
    - .deploy-production-confirmation
