include:
  - local: '/deploy/service/_fu-docker-deploy.yml'

🤞 deploy-fu-commands-dev:
  extends:
    - .docker-deploy-fu-commands
    - .deploy-development
    - .deploy-branch-rules

🤞 deploy-fu-view-dev:
  extends:
    - .docker-deploy-fu-view
    - .deploy-development
    - .deploy-branch-rules

👍 deploy-fu-commands-dev:
  extends:
    - .docker-deploy-fu-commands
    - .deploy-development
    - .deploy-tag-rules

👍 deploy-fu-view-dev:
  extends:
    - .docker-deploy-fu-view
    - .deploy-development
    - .deploy-tag-rules

🚀 deploy-fu-commands-pro:
  extends:
    - .docker-deploy-fu-commands
    - .deploy-production
    - .deploy-tag-rules
    - .deploy-production-confirmation

🚀 deploy-fu-view-pro:
  extends:
    - .docker-deploy-fu-view
    - .deploy-production
    - .deploy-tag-rules
    - .deploy-production-confirmation
