.e2e:
  stage: deploy
  dependencies: []
  needs: []
  when: manual
  variables:
    E2E_MAIN_DIR: e2e

# Common configuration in relation to the repository events that trigger E2E jobs.

.e2e-branch-rules:
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH

.e2e-tag-rules:
  rules:
    - if: $CI_COMMIT_TAG

.e2e-schedule-rules:
  rules:
    - if: $E2E_SCHEDULE_DISABLED
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
